# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:05:14+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class GoogleFirebaseFcmDataV1beta1DeliveryPerformancePercents(BaseModel):
    delayedDeviceDoze: Optional[float] = Field(
        None,
        description='The percentage of accepted messages that were delayed because the device was in doze mode. Only [normal priority messages](https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message) should be delayed due to doze mode.',
    )
    delayedDeviceOffline: Optional[float] = Field(
        None,
        description='The percentage of accepted messages that were delayed because the target device was not connected at the time of sending. These messages were eventually delivered when the device reconnected.',
    )
    delayedMessageThrottled: Optional[float] = Field(
        None,
        description='The percentage of accepted messages that were delayed due to message throttling, such as [collapsible message throttling](https://firebase.google.com/docs/cloud-messaging/concept-options#collapsible_throttling) or [maximum message rate throttling](https://firebase.google.com/docs/cloud-messaging/concept-options#device_throttling).',
    )
    delayedUserStopped: Optional[float] = Field(
        None,
        description='The percentage of accepted messages that were delayed because the intended device user-profile was [stopped](https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages) on the target device at the time of the send. The messages were eventually delivered when the user-profile was started again.',
    )
    deliveredNoDelay: Optional[float] = Field(
        None,
        description='The percentage of accepted messages that were delivered to the device without delay from the FCM system.',
    )


class GoogleFirebaseFcmDataV1beta1MessageInsightPercents(BaseModel):
    priorityLowered: Optional[float] = Field(
        None,
        description='The percentage of accepted messages that had their priority lowered from high to normal. See [documentation for setting message priority](https://firebase.google.com/docs/cloud-messaging/android/message-priority).',
    )


class GoogleFirebaseFcmDataV1beta1MessageOutcomePercents(BaseModel):
    delivered: Optional[float] = Field(
        None,
        description='The percentage of all accepted messages that were successfully delivered to the device.',
    )
    droppedAppForceStopped: Optional[float] = Field(
        None,
        description='The percentage of accepted messages that were dropped because the application was force stopped on the device at the time of delivery and retries were unsuccessful.',
    )
    droppedDeviceInactive: Optional[float] = Field(
        None,
        description='The percentage of accepted messages that were dropped because the target device is inactive. FCM will drop messages if the target device is deemed inactive by our servers. If a device does reconnect, we call [OnDeletedMessages()](https://firebase.google.com/docs/cloud-messaging/android/receive#override-ondeletedmessages) in our SDK instead of delivering the messages.',
    )
    droppedTooManyPendingMessages: Optional[float] = Field(
        None,
        description='The percentage of accepted messages that were dropped due to [too many undelivered non-collapsible messages](https://firebase.google.com/docs/cloud-messaging/concept-options#collapsible_and_non-collapsible_messages). Specifically, each app instance can only have 100 pending messages stored on our servers for a device which is disconnected. When that device reconnects, those messages are delivered. When there are more than the maximum pending messages, we call [OnDeletedMessages()](https://firebase.google.com/docs/cloud-messaging/android/receive#override-ondeletedmessages) in our SDK instead of delivering the messages.',
    )
    pending: Optional[float] = Field(
        None,
        description='The percentage of messages accepted on this day that were not dropped and not delivered, due to the device being disconnected (as of the end of the America/Los_Angeles day when the message was sent to FCM). A portion of these messages will be delivered the next day when the device connects but others may be destined to devices that ultimately never reconnect.',
    )


class GoogleTypeDate(BaseModel):
    day: Optional[int] = Field(
        None,
        description="Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
    )
    month: Optional[int] = Field(
        None,
        description='Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.',
    )
    year: Optional[int] = Field(
        None,
        description='Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleFirebaseFcmDataV1beta1Data(BaseModel):
    countMessagesAccepted: Optional[str] = Field(
        None,
        description='Count of messages accepted by FCM intended to Android devices. The targeted device must have opted in to the collection of usage and diagnostic information.',
    )
    deliveryPerformancePercents: Optional[
        GoogleFirebaseFcmDataV1beta1DeliveryPerformancePercents
    ] = Field(
        None,
        description='Additional information about delivery performance for messages that were successfully delivered.',
    )
    messageInsightPercents: Optional[
        GoogleFirebaseFcmDataV1beta1MessageInsightPercents
    ] = Field(None, description='Additional general insights about message delivery.')
    messageOutcomePercents: Optional[
        GoogleFirebaseFcmDataV1beta1MessageOutcomePercents
    ] = Field(
        None, description='Mutually exclusive breakdown of message delivery outcomes.'
    )


class GoogleFirebaseFcmDataV1beta1AndroidDeliveryData(BaseModel):
    analyticsLabel: Optional[str] = Field(
        None,
        description='The analytics label associated with the messages sent. All messages sent without an analytics label will be grouped together in a single entry.',
    )
    appId: Optional[str] = Field(
        None, description='The app ID to which the messages were sent.'
    )
    data: Optional[GoogleFirebaseFcmDataV1beta1Data] = Field(
        None, description='The data for the specified appId, date, and analyticsLabel.'
    )
    date: Optional[GoogleTypeDate] = Field(
        None, description='The date represented by this entry.'
    )


class GoogleFirebaseFcmDataV1beta1ListAndroidDeliveryDataResponse(BaseModel):
    androidDeliveryData: Optional[
        List[GoogleFirebaseFcmDataV1beta1AndroidDeliveryData]
    ] = Field(
        None,
        description='The delivery data for the provided app. There will be one entry per combination of app, date, and analytics label.',
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )
